name: Bobby Enloe Photo
favicon: null
layout_spectrum: 0.9919864609837532
typography_spectrum: 0.3979644470382482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2973261692095548
  lightness: 0.7441024342551827
  saturation: 0.11191969458013773
  rhythmicContrast: 0.9052167716436088
purpose: []
